# Site setings
name: 'Niko McCarty'
description: 'science journalist, programmer, synthetic biologist'
meta_description: 'Niko McCarty is a science journalist, data visualist, programmer, synthetic biologist in New York.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'mountain_icon.png'
  greetings: "Hi! My name is Niko, a student in the SHERP program at NYU. I'm a programmer & former synthetic biologist based in New York City."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://nikomc.github.io
disqus: 'hiniko'
mailchimp_url:
# Add your GA Tracking Id
ga_analytics: UA-77949830-3

# Contact form setings
email: nsmccarty3@gmail.com
contact_page_description: "I am most easily reached via email at nsmccarty3 [at] gmail [dot] com. Or you can use this form."
thankyou_page_description: "Thanks for your message. I will reply soon!"

# Social links
twitter: 'NikoMcCarty'
facebook: 
github: 'nikomc'
codepen: 'nsmccarty'
dribbble: 
medium: '@NikoMcCarty'
instagram:
pinterest:
linkedin: 'nsmccarty'
producthunt:
quora:

# Navigation
navigation:
  - text: Home
    url: /
  - text: Bio
    url: /bio
  - text: Writings
    url: /writings
  - text: Contact
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
  
collections:
  book_reviews:
    output: true
    output_ext: .html
    permalink: /book-reviews/:path/
